example.property= I AM THE DEFAULT

# DataSource configuration for MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ms
spring.datasource.username=root
spring.datasource.password=
spring.datasource.platform=mysql
spring.database.driverClassName=com.mysql.cj.jdbc.Driver

# JPA and Hibernate configuration for MySQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database=MYSQL
spring.jpa.show-sql=true
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# actuator management
management.endpoints.web.exposure.include=*
management.endpoints.enabled-by-default=true
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]
logging.include-application-name=false
management.tracing.sampling.probability=1.0

# eureka
eureka.instance.preferIpAddress=true
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone=http://localhost:8070/eureka/

# security and oauth relation
spring.security.oauth2.client.registration.keycloak.client-id=spring-app
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=password
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8180/realms/auth-realm
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

# kafka
action.operation.change.topic=orgChangeTopic
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.listener.observation-enabled=true

# redis
redis.server=localhost
redis.port=6379